#!/usr/bin/env ruby

require 'pathname'

if ARGV.length == 0
  STDERR.puts "Usage: files2output filename ..."
  STDERR.puts "  Prints out filename:contents pairs as a JSON object."
  STDERR.puts "  File contents are not checked to be valid JSON."
  exit 1
end

separator=''
print '{'
ARGV.each do |arg|
  fp = Pathname.new arg
  unless fp.file?
    STDERR.puts "Not a file: #{arg}"
    exit 1
  end
  print "#{separator}\"#{arg}\":"
  offset = 0
  while offset < fp.size
    print fp.read(1048576, offset)
    STDOUT.flush
    offset += 1048576
  end
  separator = ','
end
print '}'
STDOUT.flush
