#!/usr/bin/env ruby

# Copyright 2019 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See License.txt.

require 'pathname'

def usage
  STDERR.puts "Usage: files2mapped [--wait|-w] file key ..."
  STDERR.puts "  Prints out key: file contents pairs as a JSON object."
  STDERR.puts "  File contents are not checked to be valid JSON."
  STDERR.puts "  --wait/-w option will wait for a line/EOF from stdin first."
  exit 1
end

usage() if ARGV.length < 2

wait = (ARGV.first == '--wait' or ARGV.first == '-w')
ARGV.shift() if wait
usage() if (ARGV.length == 0) or (ARGV.length > 0 and ARGV.length % 2 != 0)

ARGV.each_slice(2) do |pair|
  fp = Pathname.new pair.first
  unless fp.file?
    STDERR.puts "Not a file: #{pair.first}"
    exit 1
  end
end

if wait
  begin
    STDIN.readline
  rescue StandardError
  end
end

separator=''
print '{'
ARGV.each_slice(2) do |pair|
  print "#{separator}\"#{pair.last}\":"
  fp = Pathname.new pair.first
  offset = 0
  while offset < fp.size
    print fp.read(1048576, offset)
    STDOUT.flush
    offset += 1048576
  end
  separator = ','
end
print '}'
STDOUT.flush
