task :default => [ :install ]

desc 'Clean.'
task :clean do
  `rm -f datalackeylib*.gem`
end

desc 'Build gem.'
task :build => [:clean] do
  `gem build datalackeylib.gemspec`
end

desc 'Build and install gem.'
task :install => [:build] do
  `gem install datalackeylib-*.gem`
end

desc 'Test gem.'
task :test do
  sh 'test/test_process'
end
