#!/usr/bin/python

import sys
import json

limit = int(sys.argv[1]) if len(sys.argv) > 1 else 3
data = json.load(sys.stdin)
value = data.get("data", 0)
if limit < value:
    data["exit"] = 1 # Actual value does not matter, key does.
data["data"] = value + 1
sys.stdout.write(json.dumps(data))
